//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebS.ReferenceJAVA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS/", ConfigurationName="ReferenceJAVA.ServiceGW")]
    public interface ServiceGW {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiceGW/EnviarCorreo2Request", ReplyAction="http://WS/ServiceGW/EnviarCorreo2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnviarCorreo2Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnviarCorreo2))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebS.ReferenceJAVA.EnviarCorreo2Response1 EnviarCorreo2(WebS.ReferenceJAVA.EnviarCorreo2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiceGW/EnviarCorreo2Request", ReplyAction="http://WS/ServiceGW/EnviarCorreo2Response")]
        System.Threading.Tasks.Task<WebS.ReferenceJAVA.EnviarCorreo2Response1> EnviarCorreo2Async(WebS.ReferenceJAVA.EnviarCorreo2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiceGW/helloRequest", ReplyAction="http://WS/ServiceGW/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnviarCorreo2Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnviarCorreo2))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebS.ReferenceJAVA.helloResponse1 hello(WebS.ReferenceJAVA.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServiceGW/helloRequest", ReplyAction="http://WS/ServiceGW/helloResponse")]
        System.Threading.Tasks.Task<WebS.ReferenceJAVA.helloResponse1> helloAsync(WebS.ReferenceJAVA.helloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS/")]
    public partial class helloResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS/")]
    public partial class hello : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS/")]
    public partial class EnviarCorreo2Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS/")]
    public partial class EnviarCorreo2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoDestinoField;
        
        private object[] productosField;
        
        private object[] cantidadesField;
        
        private object[] subtotalesField;
        
        private string totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CorreoDestino {
            get {
                return this.correoDestinoField;
            }
            set {
                this.correoDestinoField = value;
                this.RaisePropertyChanged("CorreoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object[] productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
                this.RaisePropertyChanged("productos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cantidades", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public object[] cantidades {
            get {
                return this.cantidadesField;
            }
            set {
                this.cantidadesField = value;
                this.RaisePropertyChanged("cantidades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subtotales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object[] subtotales {
            get {
                return this.subtotalesField;
            }
            set {
                this.subtotalesField = value;
                this.RaisePropertyChanged("subtotales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviarCorreo2", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class EnviarCorreo2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CorreoDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] productos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("cantidades", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] cantidades;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("subtotales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] subtotales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total;
        
        public EnviarCorreo2Request() {
        }
        
        public EnviarCorreo2Request(string CorreoDestino, object[] productos, object[] cantidades, object[] subtotales, string total) {
            this.CorreoDestino = CorreoDestino;
            this.productos = productos;
            this.cantidades = cantidades;
            this.subtotales = subtotales;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviarCorreo2Response", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class EnviarCorreo2Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EnviarCorreo2Response1() {
        }
        
        public EnviarCorreo2Response1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class helloResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse1() {
        }
        
        public helloResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceGWChannel : WebS.ReferenceJAVA.ServiceGW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceGWClient : System.ServiceModel.ClientBase<WebS.ReferenceJAVA.ServiceGW>, WebS.ReferenceJAVA.ServiceGW {
        
        public ServiceGWClient() {
        }
        
        public ServiceGWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceGWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebS.ReferenceJAVA.EnviarCorreo2Response1 WebS.ReferenceJAVA.ServiceGW.EnviarCorreo2(WebS.ReferenceJAVA.EnviarCorreo2Request request) {
            return base.Channel.EnviarCorreo2(request);
        }
        
        public bool EnviarCorreo2(string CorreoDestino, object[] productos, object[] cantidades, object[] subtotales, string total) {
            WebS.ReferenceJAVA.EnviarCorreo2Request inValue = new WebS.ReferenceJAVA.EnviarCorreo2Request();
            inValue.CorreoDestino = CorreoDestino;
            inValue.productos = productos;
            inValue.cantidades = cantidades;
            inValue.subtotales = subtotales;
            inValue.total = total;
            WebS.ReferenceJAVA.EnviarCorreo2Response1 retVal = ((WebS.ReferenceJAVA.ServiceGW)(this)).EnviarCorreo2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebS.ReferenceJAVA.EnviarCorreo2Response1> WebS.ReferenceJAVA.ServiceGW.EnviarCorreo2Async(WebS.ReferenceJAVA.EnviarCorreo2Request request) {
            return base.Channel.EnviarCorreo2Async(request);
        }
        
        public System.Threading.Tasks.Task<WebS.ReferenceJAVA.EnviarCorreo2Response1> EnviarCorreo2Async(string CorreoDestino, object[] productos, object[] cantidades, object[] subtotales, string total) {
            WebS.ReferenceJAVA.EnviarCorreo2Request inValue = new WebS.ReferenceJAVA.EnviarCorreo2Request();
            inValue.CorreoDestino = CorreoDestino;
            inValue.productos = productos;
            inValue.cantidades = cantidades;
            inValue.subtotales = subtotales;
            inValue.total = total;
            return ((WebS.ReferenceJAVA.ServiceGW)(this)).EnviarCorreo2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebS.ReferenceJAVA.helloResponse1 WebS.ReferenceJAVA.ServiceGW.hello(WebS.ReferenceJAVA.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WebS.ReferenceJAVA.helloRequest inValue = new WebS.ReferenceJAVA.helloRequest();
            inValue.name = name;
            WebS.ReferenceJAVA.helloResponse1 retVal = ((WebS.ReferenceJAVA.ServiceGW)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebS.ReferenceJAVA.helloResponse1> WebS.ReferenceJAVA.ServiceGW.helloAsync(WebS.ReferenceJAVA.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebS.ReferenceJAVA.helloResponse1> helloAsync(string name) {
            WebS.ReferenceJAVA.helloRequest inValue = new WebS.ReferenceJAVA.helloRequest();
            inValue.name = name;
            return ((WebS.ReferenceJAVA.ServiceGW)(this)).helloAsync(inValue);
        }
    }
}
