//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogoWeb.ReferenceWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceWS.WSSoap")]
    public interface WSSoap {
        
        // CODEGEN: Generating message contract since element name destinatario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreo", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CatalogoWeb.ReferenceWS.ArrayOfAnyType))]
        CatalogoWeb.ReferenceWS.EnviarCorreoResponse EnviarCorreo(CatalogoWeb.ReferenceWS.EnviarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.EnviarCorreoResponse> EnviarCorreoAsync(CatalogoWeb.ReferenceWS.EnviarCorreoRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidacionUsuario", ReplyAction="*")]
        CatalogoWeb.ReferenceWS.ValidacionUsuarioResponse ValidacionUsuario(CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidacionUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.ValidacionUsuarioResponse> ValidacionUsuarioAsync(CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarUsuario", ReplyAction="*")]
        CatalogoWeb.ReferenceWS.AgregarUsuarioResponse AgregarUsuario(CatalogoWeb.ReferenceWS.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.AgregarUsuarioResponse> AgregarUsuarioAsync(CatalogoWeb.ReferenceWS.AgregarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerID_User", ReplyAction="*")]
        CatalogoWeb.ReferenceWS.ObtenerID_UserResponse ObtenerID_User(CatalogoWeb.ReferenceWS.ObtenerID_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerID_User", ReplyAction="*")]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.ObtenerID_UserResponse> ObtenerID_UserAsync(CatalogoWeb.ReferenceWS.ObtenerID_UserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreo", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.EnviarCorreoRequestBody Body;
        
        public EnviarCorreoRequest() {
        }
        
        public EnviarCorreoRequest(CatalogoWeb.ReferenceWS.EnviarCorreoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CatalogoWeb.ReferenceWS.ArrayOfAnyType productos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CatalogoWeb.ReferenceWS.ArrayOfAnyType cantidades;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CatalogoWeb.ReferenceWS.ArrayOfAnyType subtotales;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string total;
        
        public EnviarCorreoRequestBody() {
        }
        
        public EnviarCorreoRequestBody(string destinatario, CatalogoWeb.ReferenceWS.ArrayOfAnyType productos, CatalogoWeb.ReferenceWS.ArrayOfAnyType cantidades, CatalogoWeb.ReferenceWS.ArrayOfAnyType subtotales, string total) {
            this.destinatario = destinatario;
            this.productos = productos;
            this.cantidades = cantidades;
            this.subtotales = subtotales;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.EnviarCorreoResponseBody Body;
        
        public EnviarCorreoResponse() {
        }
        
        public EnviarCorreoResponse(CatalogoWeb.ReferenceWS.EnviarCorreoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarCorreoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnviarCorreoResult;
        
        public EnviarCorreoResponseBody() {
        }
        
        public EnviarCorreoResponseBody(bool EnviarCorreoResult) {
            this.EnviarCorreoResult = EnviarCorreoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionUsuario", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.ValidacionUsuarioRequestBody Body;
        
        public ValidacionUsuarioRequest() {
        }
        
        public ValidacionUsuarioRequest(CatalogoWeb.ReferenceWS.ValidacionUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidacionUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public ValidacionUsuarioRequestBody() {
        }
        
        public ValidacionUsuarioRequestBody(string email, string pass) {
            this.email = email;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.ValidacionUsuarioResponseBody Body;
        
        public ValidacionUsuarioResponse() {
        }
        
        public ValidacionUsuarioResponse(CatalogoWeb.ReferenceWS.ValidacionUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidacionUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidacionUsuarioResult;
        
        public ValidacionUsuarioResponseBody() {
        }
        
        public ValidacionUsuarioResponseBody(string ValidacionUsuarioResult) {
            this.ValidacionUsuarioResult = ValidacionUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.AgregarUsuarioRequestBody Body;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(CatalogoWeb.ReferenceWS.AgregarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public AgregarUsuarioRequestBody() {
        }
        
        public AgregarUsuarioRequestBody(string email, string user, string direccion, string telefono, string pass) {
            this.email = email;
            this.user = user;
            this.direccion = direccion;
            this.telefono = telefono;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.AgregarUsuarioResponseBody Body;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(CatalogoWeb.ReferenceWS.AgregarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarUsuarioResult;
        
        public AgregarUsuarioResponseBody() {
        }
        
        public AgregarUsuarioResponseBody(string AgregarUsuarioResult) {
            this.AgregarUsuarioResult = AgregarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerID_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerID_User", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.ObtenerID_UserRequestBody Body;
        
        public ObtenerID_UserRequest() {
        }
        
        public ObtenerID_UserRequest(CatalogoWeb.ReferenceWS.ObtenerID_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerID_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public ObtenerID_UserRequestBody() {
        }
        
        public ObtenerID_UserRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerID_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerID_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CatalogoWeb.ReferenceWS.ObtenerID_UserResponseBody Body;
        
        public ObtenerID_UserResponse() {
        }
        
        public ObtenerID_UserResponse(CatalogoWeb.ReferenceWS.ObtenerID_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerID_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerID_UserResult;
        
        public ObtenerID_UserResponseBody() {
        }
        
        public ObtenerID_UserResponseBody(string ObtenerID_UserResult) {
            this.ObtenerID_UserResult = ObtenerID_UserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : CatalogoWeb.ReferenceWS.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<CatalogoWeb.ReferenceWS.WSSoap>, CatalogoWeb.ReferenceWS.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CatalogoWeb.ReferenceWS.EnviarCorreoResponse CatalogoWeb.ReferenceWS.WSSoap.EnviarCorreo(CatalogoWeb.ReferenceWS.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreo(request);
        }
        
        public bool EnviarCorreo(string destinatario, CatalogoWeb.ReferenceWS.ArrayOfAnyType productos, CatalogoWeb.ReferenceWS.ArrayOfAnyType cantidades, CatalogoWeb.ReferenceWS.ArrayOfAnyType subtotales, string total) {
            CatalogoWeb.ReferenceWS.EnviarCorreoRequest inValue = new CatalogoWeb.ReferenceWS.EnviarCorreoRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.EnviarCorreoRequestBody();
            inValue.Body.destinatario = destinatario;
            inValue.Body.productos = productos;
            inValue.Body.cantidades = cantidades;
            inValue.Body.subtotales = subtotales;
            inValue.Body.total = total;
            CatalogoWeb.ReferenceWS.EnviarCorreoResponse retVal = ((CatalogoWeb.ReferenceWS.WSSoap)(this)).EnviarCorreo(inValue);
            return retVal.Body.EnviarCorreoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.EnviarCorreoResponse> CatalogoWeb.ReferenceWS.WSSoap.EnviarCorreoAsync(CatalogoWeb.ReferenceWS.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.EnviarCorreoResponse> EnviarCorreoAsync(string destinatario, CatalogoWeb.ReferenceWS.ArrayOfAnyType productos, CatalogoWeb.ReferenceWS.ArrayOfAnyType cantidades, CatalogoWeb.ReferenceWS.ArrayOfAnyType subtotales, string total) {
            CatalogoWeb.ReferenceWS.EnviarCorreoRequest inValue = new CatalogoWeb.ReferenceWS.EnviarCorreoRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.EnviarCorreoRequestBody();
            inValue.Body.destinatario = destinatario;
            inValue.Body.productos = productos;
            inValue.Body.cantidades = cantidades;
            inValue.Body.subtotales = subtotales;
            inValue.Body.total = total;
            return ((CatalogoWeb.ReferenceWS.WSSoap)(this)).EnviarCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CatalogoWeb.ReferenceWS.ValidacionUsuarioResponse CatalogoWeb.ReferenceWS.WSSoap.ValidacionUsuario(CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest request) {
            return base.Channel.ValidacionUsuario(request);
        }
        
        public string ValidacionUsuario(string email, string pass) {
            CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest inValue = new CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.ValidacionUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.pass = pass;
            CatalogoWeb.ReferenceWS.ValidacionUsuarioResponse retVal = ((CatalogoWeb.ReferenceWS.WSSoap)(this)).ValidacionUsuario(inValue);
            return retVal.Body.ValidacionUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.ValidacionUsuarioResponse> CatalogoWeb.ReferenceWS.WSSoap.ValidacionUsuarioAsync(CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest request) {
            return base.Channel.ValidacionUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.ValidacionUsuarioResponse> ValidacionUsuarioAsync(string email, string pass) {
            CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest inValue = new CatalogoWeb.ReferenceWS.ValidacionUsuarioRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.ValidacionUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.pass = pass;
            return ((CatalogoWeb.ReferenceWS.WSSoap)(this)).ValidacionUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CatalogoWeb.ReferenceWS.AgregarUsuarioResponse CatalogoWeb.ReferenceWS.WSSoap.AgregarUsuario(CatalogoWeb.ReferenceWS.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public string AgregarUsuario(string email, string user, string direccion, string telefono, string pass) {
            CatalogoWeb.ReferenceWS.AgregarUsuarioRequest inValue = new CatalogoWeb.ReferenceWS.AgregarUsuarioRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.AgregarUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.user = user;
            inValue.Body.direccion = direccion;
            inValue.Body.telefono = telefono;
            inValue.Body.pass = pass;
            CatalogoWeb.ReferenceWS.AgregarUsuarioResponse retVal = ((CatalogoWeb.ReferenceWS.WSSoap)(this)).AgregarUsuario(inValue);
            return retVal.Body.AgregarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.AgregarUsuarioResponse> CatalogoWeb.ReferenceWS.WSSoap.AgregarUsuarioAsync(CatalogoWeb.ReferenceWS.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.AgregarUsuarioResponse> AgregarUsuarioAsync(string email, string user, string direccion, string telefono, string pass) {
            CatalogoWeb.ReferenceWS.AgregarUsuarioRequest inValue = new CatalogoWeb.ReferenceWS.AgregarUsuarioRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.AgregarUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.user = user;
            inValue.Body.direccion = direccion;
            inValue.Body.telefono = telefono;
            inValue.Body.pass = pass;
            return ((CatalogoWeb.ReferenceWS.WSSoap)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CatalogoWeb.ReferenceWS.ObtenerID_UserResponse CatalogoWeb.ReferenceWS.WSSoap.ObtenerID_User(CatalogoWeb.ReferenceWS.ObtenerID_UserRequest request) {
            return base.Channel.ObtenerID_User(request);
        }
        
        public string ObtenerID_User(string email) {
            CatalogoWeb.ReferenceWS.ObtenerID_UserRequest inValue = new CatalogoWeb.ReferenceWS.ObtenerID_UserRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.ObtenerID_UserRequestBody();
            inValue.Body.email = email;
            CatalogoWeb.ReferenceWS.ObtenerID_UserResponse retVal = ((CatalogoWeb.ReferenceWS.WSSoap)(this)).ObtenerID_User(inValue);
            return retVal.Body.ObtenerID_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.ObtenerID_UserResponse> CatalogoWeb.ReferenceWS.WSSoap.ObtenerID_UserAsync(CatalogoWeb.ReferenceWS.ObtenerID_UserRequest request) {
            return base.Channel.ObtenerID_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CatalogoWeb.ReferenceWS.ObtenerID_UserResponse> ObtenerID_UserAsync(string email) {
            CatalogoWeb.ReferenceWS.ObtenerID_UserRequest inValue = new CatalogoWeb.ReferenceWS.ObtenerID_UserRequest();
            inValue.Body = new CatalogoWeb.ReferenceWS.ObtenerID_UserRequestBody();
            inValue.Body.email = email;
            return ((CatalogoWeb.ReferenceWS.WSSoap)(this)).ObtenerID_UserAsync(inValue);
        }
    }
}
